---
- name: CREATE Consul - server_name
  consul_kv:
    scheme: "{{extra_consul.agent_scheme}}"
    validate_certs: no
    host: "{{extra_consul.agent_ip}}"
    port: "{{extra_consul.agent_port}}"
    key: "{{ extra_consul.path_source_of_truth }}/server_names/{{extra_app.name | lower}}.{{extra_app.domain | lower}}/waf"
    value: "{{ extra_app.waf }}"








...
