---
- name: CREATE Consul - server_name
  consul_kv:
    scheme: "{{extra_consul.agent_scheme}}"
    validate_certs: no
    host: "{{extra_consul.agent_ip}}"
    port: "{{extra_consul.agent_port}}"
    key: "{{ extra_consul.path_source_of_truth }}/server_names/{{extra_okta.app.name | lower}}/idp"
    value: "{{ lookup('template', 'agnostic_api-idp_info.json', split_lines='False') }}"
  when: stats_client_secret != 'none'







...
