---
- name: GET Public IP Address
  delegate_to: localhost
  azure.azcollection.azure_rm_publicipaddress_info:
    resource_group: "rg-{{ extra_platform_name }}"
    name: "devportal-{{ extra_platform_name }}"
  register: output_ip_address

- name: "Artifact for Tower Workflows"
  set_stats:
    data:
      stats_public_ip:  "{{ output_ip_address.publicipaddresses.0.ip_address }}"






...