- name: SET variables
  set_fact:
    var_env_prefix: "env_north_"
    var_instance_ids: []

- name: Retrieve the NGINX Controller auth token
  include_role:
    name: nginxinc.nginx_controller_generate_token
  vars:
    nginx_controller_fqdn: "{{extra_nginx_controller.ip}}"
    nginx_controller_user_email: "{{extra_nginx_controller.username}}"
    nginx_controller_user_password: "{{extra_nginx_controller.password}}"

### Pre-requisites - Define instances from a specific location. A location is a Azure VM Scale Set
- name: GET N+ instances ID
  uri:
    url: "https://{{ extra_nginx_controller.ip }}/api/v1/infrastructure/locations/{{ extra_app.gateways.location }}/instances"
    method: GET
    headers:
      "Cookie": "session={{ nginx_controller_auth_token }}"
    return_content: yes
    validate_certs: no
    status_code: 200
  register: instances

- name: SET var_instance_ids
  set_fact:
    var_instance_ids: "{{ var_instance_ids }} + [ {
      'name': '{{ item.metadata.name }}',
      'location': '{{ extra_app.gateways.location }}',
      'ref': '{{ item.metadata.ref }}'
    }]"
  loop: "{{ instances.json['items'] }}"

- name: Create the environment
  include_role:
    name: nginxinc.nginx_controller_environment
  vars:
    nginx_controller_fqdn: "{{extra_nginx_controller.ip}}"
    nginx_controller_environment: "{{ lookup('template','agnostic_api-environment.json') }}"

- name: Create certificate object
  include_role:
    name: nginxinc.nginx_controller_certificate
  vars:
    nginx_controller_fqdn: "{{extra_nginx_controller.ip}}"
    nginx_controller_environmentName: "{{ var_env_prefix }}{{ extra_app.environment | lower }}"
    nginx_controller_certificate: "{{ lookup('template','cert_from_survey.json') }}"
  when: extra_app_tls_key is defined

- name: Create a gateway
  include_role:
    name: nginxinc.nginx_controller_gateway
  vars:
    nginx_controller_fqdn: "{{extra_nginx_controller.ip}}"
    nginx_controller_environmentName: "{{ var_env_prefix }}{{ extra_app.environment | lower }}"
    nginx_controller_gateway: "{{ lookup('template','gateway_crt_from_survey.json') }}"

- name: Create an application
  include_role:
    name: nginxinc.nginx_controller_application
  vars:
    nginx_controller_fqdn: "{{extra_nginx_controller.ip}}"
    nginx_controller_environmentName: "{{ var_env_prefix }}{{ extra_app.environment | lower }}"
    nginx_controller_app: "{{ lookup('template','application.json') }}"

- name: Create components
  include_role:
    name: nginxinc.nginx_controller_component
  vars:
    nginx_controller_fqdn: "{{extra_nginx_controller.ip}}"
    nginx_controller_environmentName: "{{ var_env_prefix }}{{ extra_app.environment | lower }}"
    nginx_controller_appName: "app_{{ extra_app.name | lower }}.{{ extra_app.domain | lower }}"
    nginx_controller_component: "{{ lookup('template','agnostic_api-component_waf.json') }}"
  loop: "{{ extra_app.components }}"



