- name: CREATE a Location
  uri:
    url: "https://{{ extra_nginx_controller_ip }}/api/v1/infrastructure/locations/{{ extra_nginx_controller_location }}"
    method: PUT
    headers:
      "Content-Type": "application/json"
      "Cookie": "{{ stats_session }}"
    body: "{{ lookup('template','location_generic.json') }}"
    body_format: json
    return_content: yes
    validate_certs: no
    status_code: 200, 201






